export const FETCH_RANDOM_IMAGES = "FETCH_RANDOM_IMAGES";
export const FETCH_PARTICULAR_IMAGES = "FETCH_RANDOM_IMAGES";
export const FETCH_RANDOM_IMAGES_SUCCESSFUL = "FETCH_RANDOM_IMAGES";
export const FETCH_RANDOM_IMAGES_FAILED = "FETCH_RANDOM_IMAGES";
export const FETCH_PARTICULAR_IMAGES_FAILED = "FETCH_RANDOM_IMAGES";
export const FETCH_PARTICULAR_IMAGES_SUCCESSFUL = "FETCH_RANDOM_IMAGES";