import Axios from 'axios';
import {
    FETCH_PARTICULAR_IMAGES,
    FETCH_PARTICULAR_IMAGES_SUCCESSFUL,
    FETCH_PARTICULAR_IMAGES_FAILED,
    FETCH_RANDOM_IMAGES,
    FETCH_RANDOM_IMAGES_FAILED,
    FETCH_RANDOM_IMAGES_SUCCESSFUL
} from './ImageConstant'